version: '3'

services:
  login-consent-app:
    build:
      context: ./hydra-login-consent-python/
      dockerfile: ./Dockerfile
    image: login-consent-app
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    ports:
      - "${LOGIN_CONSENT_PORT}:3000"


  hydra-migrate:
    depends_on:
      - postgresd
    image: oryd/hydra:v1.8.5
    environment:
      - DSN=${DSN}
    command:
      migrate sql -e --yes
    restart: on-failure

  hydra:
    depends_on:
      - jaeger
      - hydra-migrate
    image: oryd/hydra:v1.8.5
    ports:
      - "${HYDRA_PUBLIC_PORT}:4444" # Public port
      - "${HYDRA_ADMIN_PORT}:4445" # Admin port
      - "5555:5555" # port for testing application without local installation of hydra cli
    command:
      serve all --dangerous-force-http

    environment:
      - URLS_SELF_ISSUER=${URLS_SELF_ISSUER}
      - URLS_CONSENT=${URLS_CONSENT}
      - URLS_LOGIN=${URLS_LOGIN}
      - URLS_LOGOUT=${URLS_LOGOUT}
      - SECRETS_SYSTEM=${SECRETS_SYSTEM}
      - OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=${OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES}
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=${OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT}
      - SERVE_COOKIES_SAME_SITE_MODE=${SERVE_COOKIES_SAME_SITE_MODE}
      - TRACING_PROVIDER=${TRACING_PROVIDER}
      - TRACING_PROVIDERS_JAEGER_SAMPLING_SERVER_URL=${TRACING_PROVIDERS_JAEGER_SAMPLING_SERVER_URL}
      - TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS=${TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS}
      - TRACING_PROVIDERS_JAEGER_SAMPLING_TYPE=${TRACING_PROVIDERS_JAEGER_SAMPLING_TYPE}
      - TRACING_PROVIDERS_JAEGER_SAMPLING_VALUE=${TRACING_PROVIDERS_JAEGER_SAMPLING_VALUE}
      - DSN=${DSN}
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.19.2
    ports:
      - "${JAEGER_PORT}:16686"

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
